
graphql:
  servlet:
    enabled: true
    cors:
      allowed-methods:
        - "GET"
        - "HEAD"
        - "POST"
        - "OPTIONS"
      allowed-origins:
        - "*"
        - "https://studio.apollographql.com"
  playground:
    enabled: true
    cdn:
      enabled: true

graphiql:
  cdn:
    enabled: true

server:
  port: 8081

logging:
  level:
    root: INFO

spring.datasource:
  url: jdbc:h2:file:./database.price
  driverClassName: org.h2.Driver
  username: sa
  password: password

spring:
  h2:
    console:
      enabled: true

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect