
service:
  name: basket

honeycomb:
  api:
    key: fa84da75cec2764ac882060b67287a0d
  metrics:
    dataset: gql


graphql:
  servlet:
    enabled: true
    cors:
      allowed-methods:
        - "GET"
        - "HEAD"
        - "POST"
        - "OPTIONS"
      allowed-origins:
        - "*"
        - "https://studio.apollographql.com"
      #http://localhost:3000,http://localhost:3001,https://studio.apollographql.com
  playground:
    enabled: true
    cdn:
      enabled: true
graphiql:
  cdn:
    enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO

spring.datasource:
  url: jdbc:h2:file:./database.basket
  driverClassName: org.h2.Driver
  username: sa
  password: password

spring:
  h2:
    console:
      enabled: true

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect